version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresDb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgresDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
